.github/README.md, .github/dependabot.yaml, .github/workflows/main.yaml, .github/workflows/validate.yaml, .gitignore, .terraform.lock.hcl, README.md, main.tf, repositories.tf, teams.tf
This change sets up the project with the current baseline settings for the pre-described GitHub repository settings. It includes a GitHub Action that runs on a push to pull requests to plan and validate the changes made. On a push to main, it conducts a `terraform apply`.
=> LZA-42: add initial terraform setup for repositories

repositories.tf
The poorly documented checks property was incorrect in the previous commit. This change corrects these to be the lowest level name provided, in this case the `workflow.job.name`
=> LZA-93: correct required checks

repositories.tf
The poorly documented checks property was incorrect in the previous commit. For workflows that use shared workloads the check name is the following: `<this_repo>.workflow.job.name / <shared_repo>/workflow.job.name`.
=> LZA-93: correct required checks for shared workflow

repositories.tf
This allows the superlinter action to be run against the repositories.
Due diligence has been performed on this action to ensure we are happy with adding it:
- We have 'trust by proxy' as the GitHub typescript template action uses it. 
- The 🔒 [tech-register](https://technology-register-dev.internal.cto-notprod.homeoffice.gov.uk/) does not currently contain another software marked as a linter.
- The software appears to be well maintained, with frequent updates, used by >1k repos and has 233 contributors.
- No public security issues have been reported.
=> LZA-93: add superlinter to allowed actions

repositories.tf
This allows the slack actions to be run against the repositories.
Due diligence has been performed on this action to ensure we are happy with adding it:
- We have existing repositories within the organisation that already use this action. 
- We use Slack widespread throughout the organisation.
- Whilst Slack is 'deprecated' on the 🔒 [tech-register](https://technology-register-dev.internal.cto-notprod.homeoffice.gov.uk/), it has a 2 year waiver.
- Repo hasn't had any releases in a while but is actively maintained. We could request a release though.
- No public security issues have been reported.
=> LZA-93: add slack actions to allowed actions

.github/workflows/main.yaml
=> LZA-86: add slack notification on failure

repositories.tf
=> LZA-129: bring GitHub actions repos under ownership

repositories.tf
=> LZA-126: aquasecurity to allowed actions config

repositories.tf
=> LZA-126: add repository for terraform modules

repositories.tf
=> LZA-126: add repository for platform team iam terraform

repositories.tf
=> LZA-164: add paths filter to allowed actions

repositories.tf
Previous implementation treat this as an organisation that had other actions (following previous additions). This action is on a user account, so needs a modified pattern.
I have:
=> LZA-164: update path for path filter

repositories.tf
=> fix: update Terraform modules repository to be public

repositories.tf
=> fix: add checks for tenant iam terraform

repositories.tf
=> fix: add checks for GitHub repo Terraform validation

repositories.tf
=> feat: add repository for GitHub status check action

repositories.tf
=> fix: add check for label to lza config repo

repositories.tf
=> fix: remove check from tenant iam terraform repo

repositories.tf
=> ci: add environmental status checks for iam terraform repos

repositories.tf
=> config: add required checks for repositories

repositories.tf
=> Adding terragrunt repo to create static sites

repositories.tf
=> CCL-18 - Adding Terragrunt action to allow list

.github/CODEOWNERS, repositories.tf, teams.tf
Create code owners team as a sub-team of core-cloud-devops.
Add require code owners review to main branch protection.
Give explicit write permission to code owners team to all repos - required for branch protection rule.
Once the changes are in place, I will add the required core-cloud team to the code owners team to allow them to review future PRs.
I have:
- [/ ] Validated that any resources created match the [agreed naming convention](https://collaboration.homeoffice.gov.uk/display/CORE/Naming+Convention)
=> Create code owners team as a sub-team of core-cloud-devops.

repositories.tf
=> remove check from static site repo

repositories.tf
=> Creating repository for the public DNS bootstrap poc

repositories.tf
=> CCL-278 create validator repo

repositories.tf
=> CC-6 - test/prelive static site repos
